### ISSUE TITLE
1.2.1

### ISSUE THREAD

**Issue by Wolfr** [jordienr/vue-mono-icons#1]
Hi there! We updated the icon set to 1.2.1, so it would be cool if this would be updated as well.

There's 10 new icons, and some consistency updates.

https://icons.mono.company/

**Comment by jordienr** [comment]
@Wolfr Done. I see you have removed the viewBox property from the SVGs. Is this intentional?

**Comment by Wolfr** [comment]
Hmm that may be a bit too much! I ran them through SVGO but I want to keep the viewbox. I’ll check Monday! Thanks for the notice.

**Comment by jordienr** [comment]
I'm gonna leave the issue open. If you change it leave a comment and I will update. Have a good weekend! ✌️

**Comment by Wolfr** [comment]
We fixed it in 1.2.5!

https://github.com/mono-company/mono-icons/releases/tag/1.2.5
